name: Deopy NextJS Application
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{secrets.DOCKER_HUB_USER_NAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
            - name: Build Docker Image
              run: docker build -t maheshyadav7702/next-server --build-arg REACT_APP_NODE_ENV='${{secrets.REACT_APP_NODE_ENV}}' --build-arg REACT_APP_SERVER_BASE_URL='${{secrets.REACT_APP_SERVER_BASE_URL}}'.
            - name: Publish Image to docker hub
              run: docker push maheshyadav7702/next-server:latest

    deploy: 
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull maheshyadav7702/next-server:latest
            - name: Delete old container
              run: docker rm -f mahesh-container
            - name: Run Docker Container
              run: docker run -d -p 3000:80 --name mahesh-container maheshyadav7702/next-server