name: Deploy nextjs application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "SITE_URL=${{secrets.SITE_URL}}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t maheshyadav7702/nextjs-app .
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_HUB_USER_NAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Push Docker Image to Docker Hub
        run: docker push maheshyadav7702/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from the Docker hub
        run: docker pull maheshyadav7702/nextjs-app:latest
      - name: Stop and Remove existing container
        run: docker rm -f mahesh-container  
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name mahesh-container maheshyadav7702/nextjs-app
